id: IDD9F4474
source: https://www.lotsawahouse.org
source_file: null
initial_creation_type: input
imported: '2022-05-30T20:50:39.645100'
last_modified: '2022-05-30T20:50:39.645113'
parser: null
source_metadata:
  title: Garwang Chökyi Gyaltsen
  language: bo
  description: 'Texts by and about the Fourth Shechen Rabjam, Garwang Chökyi Gyaltsen
    (gar dbang chos kyi rgyal mtshan, 1811?–1862):'
  volume:
    f62BE:
      title: A Prayer to Guru Rinpoche That Spontaneously Fulfils All Wishes (from
        the Extremely Secret Assembly of Sugatas)
      base_file: f62BE.txt
      order: 1
      parent: Prayers
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
